### ISSUE TITLE
rand64() can not generate zero

### ISSUE THREAD

**Issue by ifplusor** [flyingmutant/rand#8]
In "global_go119.go", `maphash.Bytes(maphash.MakeSeed(), nil)` can not generate zero, because `rthash(nil, 0, state)` returns `state` directly and `state` must not be 0.

**Comment by flyingmutant** [comment]
True, but I don't think it matters that much:

- wyrand itself does not generate every possible bit pattern (since its output function is not a bijection)
- probability of getting exactly zero should be 2^(-64), so it is really hard to observe the effect in practice

Top-level functions in this package should be used primarily when you require random data without synchronized shared state; right now `runtime.fastrand64` is the only option for that. In all other cases, `Rand` methods should be preferred.
